### PR TITLE
added x-checker-data for the libevdev module

### PR DESCRIPTION
**Pull request by Vilianexe**

### CODE REVIEW

**Comment by Vilianexe** [comment]
it don't update the outdated modules for the build, that's not good, because i cant see it the pattern for the url for the libevdev is correct, it only shows that's outdated :/

**Comment by Vilianexe** [comment]
ok, now, i'm more confident it's working, it gave the correct sha and version when running flatpak-external-data-checker locally

**Comment by peppy** [comment]
Can you explain what this is doing in the OP or somewhere?

**Comment by JamiKettunen** [comment]
The osu! flatpak vendors in [`libevdev`](https://www.freedesktop.org/wiki/Software/libevdev/) at version 1.12.1 currently, with [flathub/flatpak-external-data-checker](https://github.com/flathub/flatpak-external-data-checker) and this added data updates to it can be checked by which it does by scraping https://www.freedesktop.org/software/libevdev/ with the pattern specified and reports anything new found so it can be updated at times instead of forgotten about.

After this is merged since the repo already appears to be using `flatpak-external-data-checker` an update of libevdev from 1.12.1 to 1.13.1 should be included alongside the osu AppImage next time if I understand it correctly similar to https://github.com/flathub/net.rpcs3.RPCS3/commit/7aa20cc263c518a543175c52225b3b25cd1d7112.

Fwiw the RPCS3 fatpak uses a different approach but both should be ok really https://github.com/flathub/net.rpcs3.RPCS3/blob/cf2610f/net.rpcs3.RPCS3.yaml#L42-L46

**Comment by peppy** [comment]
Thanks

**Review by peppy — APPROVED** [review]

**Pull request merged**
