### PR TITLE
Update for Flathub and AppStream Compliance

### PR DESCRIPTION
**Pull request by first-storm**

### CODE REVIEW

**Comment by peppy** [comment]
Is there somewhere I can read to confirm these changes?

**Comment by first-storm** [comment]
> Is there somewhere I can read to confirm these changes?

https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/

**Comment by peppy** [comment]
Is there a reason the original `appdata` file is still there?

**Comment by peppy** [comment]
You merged master in without adding the new releases. Maybe just recreate this PR at this point with a single commit? Because you've added / deleted the file rather than used `git mv` in asingle commit the diff is not happy.

**Pull request closed without merging**
